/**
 * Israeli universities and their faculties/departments for filter dropdowns.
 */
export const UNIVERSITIES: Record<string, string[]> = {
  "Hebrew University of Jerusalem": [
    "Humanities",
    "Social Sciences",
    "Science",
    "Medicine",
    "Dental Medicine",
    "Law",
    "Agriculture, Food, and Environment",
    "Social Work & Social Welfare",
    "Business Administration",
  ],
  "Technion – Israel Institute of Technology": [
    "Engineering",
    "Sciences",
    "Architecture & Town Planning",
    "Medicine",
    "Data and Decision Sciences",
    "Education in Science & Technology",
    "Humanities and Arts",
  ],
  "Tel Aviv University": [
    "Arts",
    "Engineering",
    "Exact Sciences",
    "Humanities",
    "Law",
    "Life Sciences",
    "Medical and Health Sciences",
    "Social Sciences",
    "Management",
  ],
  "Bar-Ilan University": [
    "Jewish Studies",
    "Medicine",
    "Engineering",
    "Law",
    "Life Sciences",
    "Exact Sciences",
    "Social Sciences",
    "Education",
    "Humanities",
  ],
  "Ben-Gurion University of the Negev": [
    "Engineering Sciences",
    "Health Sciences",
    "Natural Sciences",
    "Humanities and Social Sciences",
    "Management",
    "Desert Studies",
  ],
  "University of Haifa": [
    "Humanities",
    "Social Sciences",
    "Natural Sciences",
    "Law",
    "Social Welfare and Health Sciences",
    "Education",
    "Management",
  ],
  "Weizmann Institute of Science": [
    "Biology",
    "Biochemistry",
    "Chemistry",
    "Mathematics and Computer Science",
    "Physics",
  ],
  "Open University of Israel": [
    "History, Philosophy, and Judaic Studies",
    "Language, Literature, and the Arts",
    "Mathematics and Computer Science",
    "Natural Sciences",
    "Sociology, Political Science, and Communication",
    "Management and Economics",
    "Education and Psychology",
  ],
  "Ariel University": [
    "Engineering",
    "Natural Sciences",
    "Social Sciences and Humanities",
    "Health Sciences",
    "Medicine",
  ],
  "Reichman University": [
    "Law",
    "Business",
    "Computer Science",
    "Government, Diplomacy & Strategy",
    "Communications",
    "Psychology",
    "Economics",
    "Sustainability",
  ],
};

export const UNIVERSITY_NAMES = Object.keys(UNIVERSITIES) as string[];
